# Service отвечает за стабильное DNS-имя и маршрутизацию трафика на поды Deployment.
# Через него другие сервисы обращаются к book-service внутри кластера.

apiVersion: v1
kind: Service
metadata:
  name: translation-service      
                           
  namespace: default
  labels:
    app: translation-service
    env: production

spec:
  type: ClusterIP

  selector:
    app: translation-service      


  ports:
    - name: http
      protocol: TCP
      port: 8000           
      targetPort: http     